### ISSUE TITLE
Allow user to easily set custom colors for tags and columns

### ISSUE THREAD

**Issue by guipita** [basementuniverse/vscode-kanbn#8]
I have just discovered this extension and it is great! I transferred my personal board from Trello to VScode and I am loving it, but one thing I miss is being able to easily set custom colors for different tags and columns. I don't know much about js but this go maybe go on the index.md file as another YAML entry for each. Awesome job on the extension and the CLI tool!

Edit: I know it can be done editing the css file, I would just like to know if this can be done more easily for the general user

**Comment by gordon-winkel** [comment]
Hi @pita-g, thanks for the suggestion! It would certainly be possible to add some configuration options for column/tag colors in the `index.md` YAML - something like:

```yaml
columnDisplaySettings:
  Backlog:
    colour: #00ff00
  Todo:
    colour: #ff0000
    # (maybe some other settings for each column as well, like the ability to expand/collapse columns or set the font size...)
tagDisplaySettings:
  MyCustomTag:
    foreground: #eee
    background: #333
```

These settings would override anything defined in `board.css`. My only (slight) concern is that this could lead to ambiguity; if a user has created a `board.css` _and_ defined column/tag display settings inside their `index.md`, they might wonder why their CSS file isn't working properly... however this is the type of issue that can be mitigated with good documentation :wink:

I'll think about the best way to achieve it and might include this feature in the next update.
